In [21]:
import numpy as np

In [70]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
training_inputs=np.array([[1,0,1],
                         [1,0,0],
                         [1,0,0],
                         [1,0,1]])
training_outputs=np.array([[1,0,0,1]]).T
np.random.seed(0)

In [56]:
def sigmiddd(x):
    return x*(1-x)

In [57]:
synaptic_weights=2*np.random.random((3,1))-1
print(synaptic_weights)

[[0.09762701]
 [0.43037873]
 [0.20552675]]


In [71]:
for i in range(2):
    input_layer=training_inputs
    outputs=sigmoid(np.dot(training_inputs,synaptic_weights))
    error=training_outputs-outputs
    print(error)
    adjustments=error*sigmiddd(outputs)
    synaptic_weights+=np.dot(input_layer.T,adjustments)
print("Outputs after forward training:",outputs)

[[ 0.00097118]
 [-0.00118971]
 [-0.00118971]
 [ 0.00097118]]
[[ 0.00097118]
 [-0.00118971]
 [-0.00118971]
 [ 0.00097118]]
Outputs after forward training: [[0.99902882]
 [0.00118971]
 [0.00118971]
 [0.99902882]]
